# Generated by Django 4.0.4 on 2022-04-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_notifications', '0002_alter_notification_display_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='display_type',
            field=models.IntegerField(choices=[(100, 'Bootstrap Alert'), (200, 'Modal Info'), (201, 'Modal Form'), (300, 'Activity Feed')], default=100, verbose_name='Message Type'),
        ),
    ]
