# Generated by Django 3.2.25 on 2024-12-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_notifications', '0003_alter_notification_display_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='display_type',
            field=models.IntegerField(choices=[(100, 'Bootstrap Alert'), (200, 'Modal Info'), (201, 'Modal Form'), (300, 'Activity Feed'), (400, 'Redirect')], default=100, verbose_name='Message Type'),
        ),
    ]
